# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-08 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_shoppingcart_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(help_text='订单留言', max_length=200, verbose_name='订单留言'),
        ),
    ]
